Repository Nter-developer/bravo-HealthPark-FE, pull requests merged in 2023-06, with the labels that each got.

#38 fix: 토큰 저장시 SharedPreferenceBase의 context 초기화 오류와 키값 설정 오류를 수정한다
  app/src/main/java/com/example/bravohealthpark/LoginActivity.java
  app/src/main/java/com/example/bravohealthpark/retrofit/AddCookiesInterceptor.java
  app/src/main/java/com/example/bravohealthpark/retrofit/ReceivedCookiesInterceptor.java
  app/src/main/java/com/example/bravohealthpark/retrofit/RetrofitClient.java
  app/src/main/java/com/example/bravohealthpark/retrofit/SharedPreferenceBase.java
Labels: fix

#41 feat: Setting Fragment를 일부 수정한다
  app/src/main/java/com/example/bravohealthpark/SettingFragment.java
  app/src/main/res/drawable/icon_call_center.png
  app/src/main/res/layout/activity_pref_sound.xml
  app/src/main/res/layout/fragment_setting.xml
Labels: feature

#45 refactor: 저장한 토큰으로 자동 로그인하도록 로직을 변경한다
  app/src/main/java/com/example/bravohealthpark/CustomToastMessage.java
  app/src/main/java/com/example/bravohealthpark/LoginActivity.java
  app/src/main/java/com/example/bravohealthpark/UserPreferences.java
  app/src/main/java/com/example/bravohealthpark/retrofit/AddCookiesInterceptor.java
  app/src/main/java/com/example/bravohealthpark/retrofit/LoginResponse.java
  app/src/main/java/com/example/bravohealthpark/retrofit/ReceivedCookiesInterceptor.java
  app/src/main/java/com/example/bravohealthpark/retrofit/SharedPreferenceBase.java
Labels: feature, refactoring

#48 feat: 달력 UI와 Recycler View를 구현한다
  .idea/misc.xml
  app/src/main/java/com/example/bravohealthpark/AlarmFragment.java
  app/src/main/java/com/example/bravohealthpark/CalendarActivity.java
  app/src/main/java/com/example/bravohealthpark/CalendarAdapter.java
  app/src/main/java/com/example/bravohealthpark/CalendarUtil.java
  app/src/main/res/drawable/ic_next.xml
  app/src/main/res/drawable/ic_previous.xml
  app/src/main/res/drawable/layout_color_black.xml
  app/src/main/res/drawable/shape_none_stroke.xml
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/layout/calendar_cell.xml
  app/src/main/res/layout/fragment_alarm.xml
  app/src/main/res/layout/item_weekly_caldendar_list.xml
Labels: feature

#49 feat: 약 검색 UI를 구현한다
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/bravohealthpark/AdapterActivity.java
  app/src/main/java/com/example/bravohealthpark/MainActivity.java
  app/src/main/java/com/example/bravohealthpark/SearchAdapter.java
  app/src/main/java/com/example/bravohealthpark/SearchMedActivity.java
  app/src/main/res/drawable/icon_back.png
  app/src/main/res/drawable/icon_back.xml
  app/src/main/res/drawable/icon_camera.xml
  app/src/main/res/drawable/icon_qrcode.xml
  app/src/main/res/layout/activity_med_registration.xml
  app/src/main/res/layout/activity_search_med.xml
  app/src/main/res/layout/alarm_list.xml
  app/src/main/res/layout/search_list.xml
  app/src/main/res/menu/bottom_navigation_bar.xml
Labels: feature

#57 feat: 프로젝트 전역에서 Intent와 Toast 기능을 담당할 Utils 클래스를 구현한다
  app/src/main/java/com/example/bravohealthpark/domain/medicine/domain/dto/SaveMediInfoResponse.java
  app/src/main/java/com/example/bravohealthpark/global/error/ErrorMessages.java
  app/src/main/java/com/example/bravohealthpark/global/error/ToastErrorMessage.java
  app/src/main/java/com/example/bravohealthpark/infra/utils/IntentUtils.java
  app/src/main/java/com/example/bravohealthpark/infra/utils/Messages.java
  app/src/main/java/com/example/bravohealthpark/infra/utils/ToastUtils.java
  app/src/main/java/com/example/bravohealthpark/presentation/activities/CalendarActivity.java
  app/src/main/java/com/example/bravohealthpark/presentation/activities/LoginActivity.java
  app/src/main/java/com/example/bravohealthpark/presentation/activities/MedRegistrationActivity.java
  app/src/main/java/com/example/bravohealthpark/presentation/activities/ProfEditActivity.java
  app/src/main/java/com/example/bravohealthpark/presentation/activities/SignUpActivity.java
  app/src/main/java/com/example/bravohealthpark/presentation/activities/SplashActivity.java
Labels: feature, refactoring

#59 refactor: 사용자 도메인의 비즈니스 로직을 User Manager로 분리한다
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/example/bravohealthpark/domain/authority/dto/AuthorityDto.java
  app/src/main/java/com/example/bravohealthpark/domain/medicine/domain/dto/SaveMediInfoResponse.java
  app/src/main/java/com/example/bravohealthpark/domain/medicine/domain/model/State.java
  app/src/main/java/com/example/bravohealthpark/domain/user/State.java
  app/src/main/java/com/example/bravohealthpark/domain/user/UserEntity.java
  app/src/main/java/com/example/bravohealthpark/domain/user/UserRepository.java
  app/src/main/java/com/example/bravohealthpark/domain/user/dto/FindUserResponse.java
  app/src/main/java/com/example/bravohealthpark/domain/user/service/UserManager.java
  app/src/main/java/com/example/bravohealthpark/domain/user/service/UserRetrofitService.java
  app/src/main/java/com/example/bravohealthpark/infra/persistence/UserRepositoryImpl.java
  app/src/main/java/com/example/bravohealthpark/infra/preferences/UserPreferences.java
  app/src/main/java/com/example/bravohealthpark/infra/retrofit/UserManagerImpl.java
  app/src/main/java/com/example/bravohealthpark/presentation/activities/LoginActivity.java
  app/src/main/java/com/example/bravohealthpark/presentation/activities/MainActivity.java
  app/src/main/java/com/example/bravohealthpark/presentation/activities/SignUpActivity.java
  app/src/main/java/com/example/bravohealthpark/presentation/fragments/HomeFragment.java
Labels: feature, refactoring

#61 feat: OCR 약 등록을 위한 카메라 전환 기능과 통신 로직을 구현한다
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/bravohealthpark/domain/medication/State.java
  app/src/main/java/com/example/bravohealthpark/domain/medication/Time.java
  app/src/main/java/com/example/bravohealthpark/domain/medication/dto/SaveMediInfoRequest.java
  app/src/main/java/com/example/bravohealthpark/domain/medication/dto/SaveMediInfoResponse.java
  app/src/main/java/com/example/bravohealthpark/domain/medication/dto/SendImageRequest.java
  app/src/main/java/com/example/bravohealthpark/domain/medication/dto/SendImageResponse.java
  app/src/main/java/com/example/bravohealthpark/domain/medication/services/MediInfoRetrofitService.java
  app/src/main/java/com/example/bravohealthpark/domain/medicine/services/MedicationInfoService.java
  app/src/main/java/com/example/bravohealthpark/domain/user/State.java
  app/src/main/java/com/example/bravohealthpark/infra/utils/ConvertUtils.java
  app/src/main/java/com/example/bravohealthpark/presentation/activities/AdapterActivity.java
  app/src/main/java/com/example/bravohealthpark/presentation/activities/MainActivity.java
  app/src/main/java/com/example/bravohealthpark/presentation/activities/MedRegistrationActivity.java
  app/src/main/java/com/example/bravohealthpark/presentation/fragments/CameraFragment.java
  app/src/main/res/layout/fragment_camera.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: feature

#63 feat: 알람 생성 기능을 위한 리사이클러뷰를 구현한다
  app/build.gradle
  app/src/main/java/com/example/bravohealthpark/domain/alarm/AlarmItem.java
  app/src/main/java/com/example/bravohealthpark/domain/alarm/DoseState.java
  app/src/main/java/com/example/bravohealthpark/presentation/activities/MainActivity.java
  app/src/main/java/com/example/bravohealthpark/presentation/adapters/RecyclerViewAdapter.java
  app/src/main/java/com/example/bravohealthpark/presentation/fragments/AlarmFragment.java
  app/src/main/res/drawable/shape_add_alarm.xml
  app/src/main/res/layout/fragment_alarm.xml
  app/src/main/res/layout/item_alarm.xml
Labels: feature

#65 feat: 서버와의 통신을 통한 알람 생성 기능을 구현한다
  app/src/main/java/com/example/bravohealthpark/domain/alarm/Alarm.java
  app/src/main/java/com/example/bravohealthpark/domain/alarm/AlarmTime.java
  app/src/main/java/com/example/bravohealthpark/domain/alarm/Meal.java
  app/src/main/java/com/example/bravohealthpark/domain/alarm/dto/CreateAlarmRequest.java
  app/src/main/java/com/example/bravohealthpark/domain/alarm/dto/CreateAlarmResponse.java
  app/src/main/java/com/example/bravohealthpark/domain/alarm/service/AlarmRetrofitService.java
  app/src/main/java/com/example/bravohealthpark/presentation/fragments/AlarmFragment.java
  app/src/main/res/layout/fragment_alarm.xml
Labels: feature
